[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip ATSAMD51G19A --protocol swd --speed 4000"

rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x"
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "debug"
